### ISSUE TITLE
[Windows] Launching the game "fries" my Wi-Fi driver

### ISSUE THREAD

**Issue by Voltra** [edo9300/edopro#270]
Launching the game (latest version I could get before the bug) on Windows 11 results in my Wi-Fi driver (Intel Wireless AC-9560 160MHz, which is up to date) becoming corrupted after a few seconds and needing to be re-installed/repaired

Last log entries in `error.log`:
```
[2024-05-17 21:51:46] Warning occurred in repo https://github.com/ProjectIgnis/Puzzles: failed to resolve address for github.com: Unknown host. 
[2024-05-17 21:51:46] Warning occurred in repo https://github.com/ProjectIgnis/DeltaPuppetOfStrings: failed to resolve address for github.com: Unknown host. 
[2024-05-19 11:35:02] Warning occurred in repo https://github.com/ProjectIgnis/DeltaPuppetOfStrings: indexer progress callback returned -1
```

**Comment by edo9300** [comment]
That sure is a new kind of bug, even tho it's highly unprobable the issue is caused by edopro, as an userspace program shouldn't have the priviledges to be able to completely kill the network stack of the os. Searching online for your network card, shows that you're not the only person who has the card randomly dying on him, requiring a driver reinstall to get it working again (and sometime that isn't even enough). If you can, you should try that card under another OS, even Windows 10, and see if you get the same issues, also, if you're using windows update drivers, you could try to use the drivers directly provided by the manufacturer itself, in your case intel, and see if they make any difference.
Regardless, on edopro's side, if what's breaking things is the repo cloning as the logs could be suggesting, then that's something even outside my control, as that's done by an external library, and I also think that if this issue was an actual bug in that library, it would've been reported by other people for other programs as well.

**Comment by Voltra** [comment]
I'll try to dig deeper and see what's going on

**Comment by Voltra** [comment]
It'll probably be unrelated to EDOPro. Lately it's been happening with other things.

I think the latest Windows 11 update broke some shared library somewhere, and anything that does a fair amount of network (possibly just HTTP) requests can cause it to fry :'c

Or just an OS-driver incompatibility issue
