### ISSUE TITLE
LAN Mode: Relays pass the Graveyard along

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#86]
Though this makes it more similar to Tag Duels, these zones are actually not passed along in the anime. Perhaps this could be an option to choose the type of behaviour?

**Comment by edo9300** [comment]
The graveyard isn't switched as because of the way the core is structured, there will be issues with resolving effects that won't be easily clearable because of lack of rulings for an unofficial game rule. Also this side in the anime wasn't very clear, as the only possible evidence was using a trap to copy teh effect of a monster in the graveyard before changing player, so it can only be assumed the graveyard was switched.
